// Generated by CoffeeScript 1.6.3
(function() {
  var cli, commands, dlog;

  dlog = require('debug')('perc');

  commands = require('./commands');

  cli = require('./cli');

  exports.run = function() {
    dlog('run: ', process.argv.slice(2));
    return cli.run(process.argv.slice(2), commands);
  };

}).call(this);
