// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    build: require('./build'),
    check: require('./check'),
    init: require('./init'),
    test: require('./test'),
    watch: require('./watch')
  };

}).call(this);
