var Item, ViewModel, dlog, ko, load, util;

dlog = require('debug')('sample-project:view:main');

ko = require('../includes/knockout');

ko.mapping = require('../includes/knockout.mapping');

Item = require('../model/item').Item;

util = require('../util');

require('../bindings');

require('../includes/jquery');

ViewModel = (function() {

  ViewModel.prototype.mapping = {
    items: {
      key: util.fromid,
      create: function(options) {
        return new Item(options.data, this);
      }
    }
  };

  function ViewModel(url) {
    var _this = this;
    this.url = url;
    dlog('viewmodel for', this.url);
    this.ready = ko.observable(false);
    $.getJSON(this.url, function(data) {
      return _this.refresh(data);
    });
  }

  ViewModel.prototype.refresh = function(data) {
    dlog('refresh', this, data);
    ko.mapping.fromJS(data, this.mapping, this);
    return this.ready(true);
  };

  return ViewModel;

})();

load = function(url) {
  var vm;
  vm = new ViewModel(url);
  ko.applyBindings(vm);
  return vm;
};

module.exports.load = load;

// Generated by CoffeeScript 1.5.0-pre
